### PR TITLE
Create "Call to Action" Card

### PR DESCRIPTION
**Pull request by tomstepp**
Fixes Issue: https://github.com/bitprj/bit-frontend/issues/7#issue-602282127
Notes:

- I couldn't tell if the icons were "pre-made" or not. I thought using react-icons was a simple & easy solution.
- I couldn't tell from the issue description if the icons must look exactly as they were in the sample images. Or if it was simply a mock-up.
- Should I add a property for a call-back method? I think I need to make these cards click-able so they can start/stop a video?
Examples:
Screen Shot 2020-04-17 at 8 05 06 PM

### CODE REVIEW

**Comment by poroia** [comment]
Hey Tom!

Awesome work! We forgot to send you a link the Figma, where we prototype our designs. [Here it is](https://www.figma.com/file/pyXHrfSlr2xx3xunNXjcpx/New-UI). From here, you're able to extract the icons created using the 'Export' feature on a particular item's menu. Eventually, I believe we'll have these SVG icons custom designed and they'll all be hosted on our s3 but for now, we're using this method or pulling icons from [Material Ui's icons](https://material-ui.com/components/material-icons/). 

In regards to the callback, ensuring that React `onClick` event function gets passed to the root component will allow actions to be taken on them.

**Comment by poroia** [comment]
In regards to the next steps, if you can reimplement the icons using the ones from Figma or Material UI, and pass the onClick function to the root component of ActionCard, that would be great!

**Comment by tomstepp** [comment]
Where in the Figma are these icons? The Material UI icons do not look close enough to the desired outcome.

**Comment by tomstepp** [comment]
Ok, I see them there now. Just not sure how to use them from Figma...

**Comment by tomstepp** [comment]
@poroia can you please review again? I made the updates requested.

**Comment by tomstepp** [comment]
Screen Shot 2020-04-17 at 10 17 25 PM

**Pull request closed without merging**
